export const fontss = [
  "Advent Pro",
  "Alegreya",
  "Alegreya Sans SC",
  "Alegreya SC",
  "Alex Brush",
  "Alfa Slab One",
  "Allerta Stencil",
  "Amatic SC",
  "Anonymous Pro",
  "Anton",
  "Arima Madurai",
  "Arvo",
  "Assistant",
  "Audiowide",
  "Averia Sans Libre",
  "Averia Serif Libre",
  "Baloo Bhai",
  "Baloo Bhaina",
  "Bangers",
  "Barrio",
  "BenchNine",
  "Bonbon",
  "Boogaloo",
  "Bowlby One SC",
  "Bungee Inline",
  "Bungee Shade",
  "Butcherman",
  "Butterfly Kids",
  "Cabin",
  "Catamaran",
  "Caveat",
  "Ceviche One",
  "Cinzel Decorative",
  "Clicker Script",
  "Codystar",
  "Cormorant",
  "Cormorant Garamond",
  "Creepster",
  "Crimson Text",
  "Cutive Mono",
  "Dancing Script",
  "Diplomata SC",
  "Eagle Lake",
  "Exo",
  "Expletus Sans",
  "Faster One",
  "Finger Paint",
  "Fira Sans",
  "Fjalla One",
  "Fredericka the Great",
  "Frijole",
  "Gochi Hand",
  "Grand Hotel",
  "Great Vibes",
  "Hanalei Fill",
  "Handlee",
  "Heebo",
  "Josefin Slab",
  "Kalam",
  "Kanit",
  "Karla",
  "Khula",
  "Knewave",
  "Lato",
  "League Script",
  "Leckerli One",
  "Libre Franklin",
  "Lilita One",
  "Lobster Two",
  "Londrina Outline",
  "Lora",
  "Love Ya Like A Sister",
  "Luckiest Guy",
  "Mallanna",
  "Meddon",
  "Merriweather",
  "Metal Mania",
  "Modak",
  "Monoton",
  "Montez",
  "Montserrat",
  "Mr Dafoe",
  "Mrs Sheppards",
  "New Rocker",
  "Niconne",
  "Nobile",
  "Nosifer",
  "Nothing You Could Do",
  "Open Sans",
  "Overlock",
  "Pacifico",
  "Parisienne",
  "Passion One",
  "Patrick Hand",
  "Permanent Marker",
  "Piedra",
  "Pinyon Script",
  "Playfair Display",
  "Playfair Display SC",
  "Poppins",
  "Prompt",
  "Proza Libre",
  "Quicksand",
  "Raleway",
  "Rancho",
  "Ribeye Marrow",
  "Righteous",
  "Roboto",
  "Roboto Condensed",
  "Rochester",
  "Rubik",
  "Ruslan Display",
  "Sacramento",
  "Satisfy",
  "Seaweed Script",
  "Shrikhand",
  "Sigmar One",
  "Sofia",
  "Sonsie One",
  "Source Sans Pro",
  "Special Elite",
  "Spicy Rice",
  "Spirax",
  "Sriracha",
  "Stalemate",
  "Sue Ellen Francisco",
  "Teko",
  "Tinos",
  "Trade Winds",
  "Trirong",
  "Tulpen One",
  "Ubuntu",
  "Wallpoet",
  "Walter Turncoat",
  "Wire One",
  "Work Sans",
  "Yanone Kaffeesatz",
  "Yantramanav",
  "Yellowtail",
];
